# eGestor API

Recursos disponíveis para acesso via API:
* [**Produtos**](#reference/recursos/produtos)

## Respostas

| Código | Descrição |
|---|---|
| `200` | Requisição executada com sucesso (success).|
| `400` | Erros de validação ou os campos informados não existem no sistema.|
| `401` | Dados de acesso inválidos.|
| `404` | Registro pesquisado não encontrado (Not found).|
| `405` | Método não implementado.|
| `410` | Registro pesquisado foi apagado do sistema e não esta mais disponível.|
| `422` | Dados informados estão fora do escopo definido para o campo.|
| `429` | Número máximo de requisições atingido. (*aguarde alguns segundos e tente novamente*)|

## Listar
As ações de `listar` permitem o envio dos seguintes parâmetros:

| Parâmetro | Descrição |
|---|---|
| `filtro` | Filtra dados pelo valor informado. |
| `page` | Informa qual página deve ser retornada. |

# Produtos [/produtos]

Produtos são utilizados nas vendas e controle de estoque.


### Listar (List) [GET /produtos{?filtro,codCategoria,controlarEstoque,tipoUso,arquivado,anotInternas,Norig,INCM,codConfigTrib,IcProd,updatedBefore,updatedAfter,fields,orderBy}]

+ Parameters
    + filtro (optional) - Busca a string informada nos campos: código do produto, código próprio e nome do produto.
    + codCategoria (optional, integer) - Código da categoria do produto.
    + controlarEstoque (optional, integer) - Filtra por produtos que controlam/não controlam estoque. Valores possíveis:
      * 0 - Não controla estoque
      * 1 - Controla estoque
    + tipoUso (number, optional) - Tipo de uso do produto
        * 0 - Mercadoria para revenda
        * 1 - Matéria-prima
        * 2 - Embalagem
        * 3 - Produtos em processo
        * 4 - Produto final (Produção)
    + arquivado (boolean, optional) - Filtra apenas por produtos arquivados
    + Norig (optional, integer) - Origem do produto. Valores possíveis:
      * 0 - Nacional, exceto as indicadas nos códigos de 3, 4, 5 e 8',
      * 1 - Estrangeira, importação direta, exceto a indicada no código 6',
      * 2 - Estrangeira, adquirida no mercado interno, exceto a indicada no código 7',
      * 3 - Nacional, mercadoria ou bem com Conteúdo de Importação maior que 40% e menor ou igual a 70%',
      * 4 - Nacional, produção em conformidade com processos básicos que tratam as legisl. dos Ajustes',
      * 5 - Nacional, mercadoria ou bem com Conteúdo de Importação inferior ou igual a 40%',
      * 6 - Estrangeira, importação direta, sem similar nacional, constante na lista da CAMEX e gás natural',
      * 7 - Estrangeira, adquir. merc. interno, sem similar nacional, na lista da CAMEX e gás natural',
      * 8 - Nacional, mercadoria ou bem com Conteúdo de Importação superior a 70%'
    + INCM (optional, integer) - NCM dos produtos
    + codConfigTrib (optional, integer) - Código do grupo de tributos vinculado.
    + IcProd (optional, string) - Código interno do produto
    + anotInternas (optional, string) - Filtro baseado nas observações internas do produto
    + updatedBefore (optional, string) - Lista apenas produtos que sofreram alterações antes da data informada. Formato "YYYY-MM-DD HH:MM:SS"
    + updatedAfter (optional, string) - Lista apenas produtos que sofreram alterações após a data informada. Formato "YYYY-MM-DD HH:MM:SS"
    + fields (optional) - Permite definir quais os campos serão retornados pela api. Informe separado por vírgula.
      * ex: &fields=descricao,codigoProprio
    + orderBy (optional) - Permite definir a ordenação da listagem. Informe o campo e a forma de ordenação (ascendente ou descendente) separados por vírgula. Só é possível definir uma ordenação por requisição. Valores possíveis:
        * codigo, codCategoria, descricao, codigoProprio, estoque, estoqueMinimo, controlarEstoque, margemLucro, precoCusto, precoVenda, origemFiscal, unidadeTributada, refEanGtin, ncm, excecaoIPI, codigoCEST, pesoBruto, pesoLiquido, anotacoesNFE, anotacoesInternas, tags, dtCad
        * ex: &orderBy=margemLucro,desc
        * ex: &orderBy=descricao,asc

+ Request (application/json)
